= Test-Plan

Dieser Testplan stellt eine vereinfachte Version der IEEE 829-1998 Vorlage dar.

== Einführung
Wozu dient das Dokument? Zielgruppe?

== Aufbau der Testbezeichner
Nach welchem Schema sind die Tests benannt?

1. Buchstabe: Zugehörigkeit des Departments +
U - UserDepartment, P - PlotDepartment, F - FinanceDeparment, M - MessageDepartment
2. Buchstabe: Art des Tests +
U - UnitTest, I - Integrationstest
3. fortlaufende  Zahl zu Identifikation des Tests im jeweiligen Department

Bsp. +
U-U-01, P-U-02, F-I-03

== Test Gegenstände
Test Gegenstände sind die jeweiligen Verwaltungsebenen, bzw. die ausführenden Klassen (z.B. Controller).

== Zu testende Funktionalitäten
Zu testen sind die eigenen erstellten Klassen, welche die Eingaben entgegennehmen, diese verarbeiten oder an andere Bereiche weitergeben.

== Nicht zu testende Funktionalitäten
Bibliotheken von Drittanbietern (eigene Tests beschränken sich auf Schnittstelle, bzw. Zusammenspiel).
Zu diesen gehören beispielsweise Spring, Salespoint, Maven, Thymeleaf.

== Herangehensweise
- Klassen werden mit JUnit getestet.
- Integrationstest nach Bottom-Up Prinzip

== Umgebungsvoraussetzungen
* Wird spezielle Hardware benötigt?
* Welche Daten müssen bereitgestellt werden? Wie werden die Daten bereitgestellt?
* Wird zusätzliche Software für das Testen benötigt?
* Wie kommuniziert die Software während des Testens? Internet? Netzwerk?

== Testfälle und Verantwortlichkeit
Jede testbezogene Aufgabe muss einem Ansprechpartner zugeordnet werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|…  |…              |…              |…       |…
|===
