= Test-Plan

Dieser Testplan stellt eine vereinfachte Version der IEEE 829-1998 Vorlage dar.

== Einführung
Dieses Dokument soll einen Überblick geben, wie getestet werden soll, inwiefern die Qualität der Anwendung gewährleistet wird.
Dabei werden die zu betrachteten Teilbereiche, die verwendeten Testverfahren und notwendige Rahmenbedingungen festgelegt.

Ebenfalls soll es für das Entwicklerteam eine Unterstützung bei ihrer Arbeit sein und unabhängigen Bewertern die Möglichkeit bieten,
die Qualität der Anwendung einzuschätzen.

== Aufbau der Testbezeichner
Nach welchem Schema sind die Tests benannt?

1. Buchstabe: Zugehörigkeit des Departments +
T - TenantDepartment, P - PlotDepartment, F - FinanceDeparment, M - MessageDepartment
2. Buchstabe: Art des Tests +
U - UnitTest, I - Integrationstest
3. fortlaufende  Zahl zu Identifikation des Tests im jeweiligen Department

Bsp. +
U-U-01, P-U-02, F-I-03

== Test Gegenstände
Test Gegenstände sind die jeweiligen Verwaltungsebenen, bzw. die ausführenden Klassen (z.B. Controller).

== Zu testende Funktionalitäten
Zu testen sind die eigenen erstellten Klassen, welche die Eingaben entgegennehmen, diese verarbeiten oder an andere Bereiche weitergeben.

== Nicht zu testende Funktionalitäten
Bibliotheken von Drittanbietern (eigene Tests beschränken sich auf Schnittstelle, bzw. Zusammenspiel).
Zu diesen gehören beispielsweise Spring, Salespoint, Maven, Thymeleaf.

== Herangehensweise
- Klassen werden mit JUnit getestet.
- Integrationstest nach Bottom-Up Prinzip

== Umgebungsvoraussetzungen
*  Ein einsatzfähiges Computer System
* Zu testende Programme (Testobjekte)
* JUnit zur Erstellung von Unit Tests

== Testfälle und Verantwortlichkeit



==== TenantDepartment
zuständig: Isabell Zorr
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|  |              |…              |…       |…
|===

==== PlotDepartment
zuständig: Ylvi Sarah Bachmann und Albert Wellerdt

[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|P-U-010 |Parzelle erstellen|…              |…       |…
|===

==== FinanceDepartment
zuständig: Sanghyun Lee und Sascha Seiffert
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|…  |…              |…              |…       |…
|===

== PlotDepartment
zuständig Ylvi Sarah Bachmann und Albert Wellerdt

[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|P-U-010 |Parzelle erstellen |--      |Parzellengröße, Bereich, Schätzwert, Wasserzähler, Stromzähler | Parzelle wird erstellt, Attribute in passendem Format
|P-U-012 |Parzelle besetzt |Bewerbung angenommen      |Email des neuen Pächters dann auf besetzt | String "besetzt" wird ausgegeben
|===


==== MessageDepartment
zuständig: Muhammad Talal Anwar
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|P-U-010 |Parzelle erstellen |--      |Parzellengröße, Bereich, Schätzwert, Wasserzähler, Stromzähler | Parzelle wird erstellt, Attribute in passendem Format
|P-U-012 |Parzelle besetzt |Bewerbung angenommen      |Email des neuen Pächters dann auf besetzt | String "besetzt" wird ausgegeben
|…  |…              |…              |…       |…
|===

