= Zeiterfassung für Gruppe 43

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

Werte in () beinhalten sowohl Einzelarbeitszeit, als auch Meetings der Gruppe 44, aus den Wochen bevor der Wechsel zur Gruppe 43 stattfand.

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
| Woche | Albert | Franziska | Isabell | Sanghyun | Talal | Ylvi   | Sascha | Meeting
| 1     | 370    | 660       | 360     | 480      | 480   | (990)  | (380)  | 200
| 2     | 400    | 460       | 400     | 450      | 400   | (1059) | (310)  | 180
| 3     | 1400   | 1300      | 800     | 780      | 1080  | (1798) | (698)  | 410
| 4     | 420    | 420       | 480     | 400      | 300   | (891)  | (555)  | 90
| 5     | 1000   | 1000      | 1110    | 750      | 900   | 426    | 270    | 320
| 6     | …      | 630       | 650     | 420        | …     | 526    | 60     | 240
| 7     | …      | …         | …       | …        | …     | …      |        |
| 8     | …      | …         | …       | …        | …     | …      |        |
| 9     | …      | …         | …       | …        | …     | …      |        |
| 10    | …      | …         | …       | …        | …     | …      |        |
| 11    | …      | …         | …       | …        | …     | …      |        |
| 12    | …      | …         | …       | …        | …     | …      |        |
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
