= Protokoll Gruppe 43

Treffen am 20.10.2019

Ort:      Andreas-Pfitzmann-Bau +
Beginn:   10:00 Uhr +
Ende:     13:30 Uhr

__Schriftführer:__Isabell Zorr

*Nächstes Treffen:* +
23.10.2019, 13:00 Uhr, SLUB

__Teilnehmer:__
//Tabellarisch oder Aufzählung, Kennzeichnung von Teilnehmern mit besonderer Rolle (z.B. Kunde)

- Albert Wellerdt
- Franziska Kiel
- Muhammad Talal Anwar
- Sanghyun Lee
- Isabell Zorr


== Bemerkungen
Wir haben die Analysediagramme unserer Anwendung erstellt und sind zusammen die Aufgabenstellung
durchgegangen, haben Verständnisfragen geklärt und Fragen für das Kundengespräch formuliert. Erste
Ideen zur Implementation wurden gesammelt.

== Retrospektive des letzten Sprints
Jedes Teammitglied hat die Aufgabenstellung gelesen und jeder implementierte eine Erweiterung im
Guestbook-Prototyp.

== Aktueller Stand
Der aktuelle Stand der Software befindet sich noch in der Analysephase. Die Aufgabenstellung wurde
gelesen und Fragen für das Kundengespräch formuliert.

== Planung des nächsten Sprints
Da im nächsten externen Treffen das Kundengespräch abgehalten wird, müssen weitere Fragen formuliert
werden.
