= Protokoll Gruppe 43

Treffen am 28.10.2019

Ort:      APB +
Beginn:   12:50 Uhr +
Ende:     14:30 Uhr

__Schriftführer:__ Isabell Zorr

*Nächstes Treffen:* +
06.11.2019, 13:00 Uhr, APB

__Teilnehmer:__
//Tabellarisch oder Aufzählung, Kennzeichnung von Teilnehmern mit besonderer Rolle (z.B. Kunde)

- Albert Wellerdt
- Franziska Kiel
- Sanghyun Lee
- Isabell Zorr

== Bemerkungen
Wir haben die CRC-Karten besprochen und für die Anwendung der CRC-Karten-Methode vorbereitet. Zudem
haben wir das Pflichtenheft besprochen und am Beispiel vom Videoshop

== Retrospektive des letzten Sprints
Jeder hat ein bis zwei CRC-Karten verfasst.
Franziska und Isabell erstellten die für den Nebenpächter und den Obmann, Sanghyun für den Hauptpächter,
Talal für den Gast und Albert für den Vorstandsvorsitzenden, Kassierer, der Person und dem Stellvertretenden.

== Aktueller Stand

Das Pflichtenheft ist in Bearbeitung und wird am Freitag abgegeben. Damit wird die
Analysephase am Freitag beendet und die Entwurfsphase beginnt nächste Woche.

== Planung des nächsten Sprints
Das Pflichtenheft wird bis Freitag fertiggestellt, sowie die Erweiterungen für den Videoshop.
Bei Bedarf wird sich in einem Gruppencall bei Discord getroffen und letzte liegengebliebene Sachen geklärt.
