= Protokoll Gruppe 43

Treffen am 23.10.2019

Ort:      SLUB +
Beginn:   13:00 Uhr +
Ende:     14:50 Uhr

__Schriftführer:__Isabell Zorr

*Nächstes Treffen:* +
26.10.2019, 10:00 Uhr, APB

__Teilnehmer:__
//Tabellarisch oder Aufzählung, Kennzeichnung von Teilnehmern mit besonderer Rolle (z.B. Kunde)

- Albert Wellerdt
- Franziska Kiel
- Sanghyun Lee
- Isabell Zorr

== Bemerkungen
Wir arbeiteten die bereits erstellten Analysediagramme weiter aus
und ergänzten neue Teile, die im Kundengespräch erfahren wurden.

== Retrospektive des letzten Sprints

Mit den im letzten Sprint formulieren Fragen konnten viele neue Erkenntnisse aus dem Kundengespräch
erfahren werden, die nun in die Analyse eingehen werden.


== Aktueller Stand
Das Kundengespräch lieferte neue Erkenntnisse und konnte Fragen klären. Die neuen Informationen
und Wünsche des Kunden werden in die Analysediagramme übertragen und ins Pflichtenheft aufgenommen.

== Planung des nächsten Sprints
Im nächsten Sprint werden die Sequenzdiagramme zum Bewerben auf eine Parzelle (Franziska und Isabell),
das Erstellen und Versenden einer Rechnung (Talal) und zum Bewerben und Anrechnen von Pflichtstunden (Sanghyun)
ausgearbeitet.