= Protokoll Gruppe 43

Treffen am 23.10.2019

Ort:      Ort des Treffens +
Beginn:   07:30 Uhr +
Ende:     09:05 Uhr

__Schriftführer:__ Isabell Zorr

*Nächstes Treffen:* +
30.10.2019, 07:30 Uhr, Andreas-Pfitzmann-Bau

__Teilnehmer:__
//Tabellarisch oder Aufzählung, Kennzeichnung von Teilnehmern mit besonderer Rolle (z.B. Kunde)

- Uwe Schmidt (Tutor)
- Albert Wellerdt
- Franziska Kiel
- Muhammad Talal Anwar
- Sanghyun Lee
- Isabell Zorr

== Bemerkungen
Wir haben uns noch einmal in der Gruppe vorgestellt und die Ziele des Praktikums und
unsere eigenen Vorstellungen an dieses besprochen. Zudem wurden die Abgaben aus den
Guestbookerweiterungen abgenommen und Tipps zur Verbesserung gegeben.
Hauptaspekt des Treffens war das "Kundengespräch", welches
wir nutzten um unsere Anwendung weiter zu planen und Fragen zu klären.

== Retrospektive des letzten Sprints

Die Guestbookerweiterungen wurden fertiggestellt und sollten einen ersten Einblick in das Spring-Framework
geben. Die Gruppenmitglieder haben sich in die Aufgabenstellung eingelesen und aufgrund dessen Fragen
für das Kundengespräch verfasst.

== Aktueller Stand
Der aktuelle Stand der Software befindet sich noch in der Analysephase.
Es wurden CRC-Karten und Analysediagramme erstellt, welche weiter ausgearbeitet werden.

== Planung des nächsten Sprints
Es müssen die Analysediagramme in Magicdraw erstellt werden und das Pflichtenheft wird begonnen.