= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2019/20
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Franziska Kiel

**Gruppe:** 43

== Was habe ich gelernt?
- Arbeit mit Frameworks
- Aufbau und Planung großer Projekte (z.B. wie wichtig die Analysephase ist, um große Probleme bei der Implementierung zu vermeiden)
- Java Kenntnisse
- Arbeit mit HTML

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
Unser Team bestand am Anfang aus 5 Leuten. Die Kommunikation innerhalb der Gruppe gestalltete sich sehr schwierig,
da schon eine gemeinsame Terminfindung anfangs unmöglich schien. Daher hat meistens immer ein Teammitglied bei den internen
Meetings gefehlt, was die Absprache umso schwieriger gestalltete. Deshalb führten wir Absprachen über Discord ein, jedoch
nahmen diesen Termin auch nicht alle war. Die Kommunikation blieb daher auf einem Minimum, was übermäßig zu Einzelarbeiten führte
und Probleme in dem Projekt hervorruf. Zudem kamen mitten im Projekt noch zwei weitere Teammjtglieder hinzu, was die Aufgabenverteilung
stark komplizierte. Wir arbeiteten hauptsächlich jeder für sich, als zusammen im Team, weshalb wir starke Probleme hatten,
die einzelnen Bausteine zusammenzuführen. Deshalb mussten wir teilweise die Strukturen von Grundauf neu aufarbeiten und verändern,
wodruch wir starke Zeitprobleme bekamen. Die Kommunikation und Zusammenarbeit wurde jeodch daraufhin besser.
Von den 6 Mitgiedern kannte ich bereits eine Person sehr gut, was zumindest die Verständigung zwischen uns beiden sehr stark
vereinfachte. So haben wir beide zumindest einige Absprachen treffen und Probleme lösen können, wenn der Rest der Gruppe
gerade keine Meinung äußerte. Bereits bekannte Personen in der Gruppe zu haben hat vor allem den Vorteil, dass man deren
Stärken und Schwächen kennt und
dass man sich auf diese Person verlassen kann und ihnen vertraut, dass sie ihre Arbeit gewissenhaft erledigen. Bei fremden
Leuten ist das eher schwierig, wodurch man manchmal unangenehme Überraschungen erlebt. Gerade zum Schluss gab es ein Mitglied,
dass seine Arbeiten nicht mehr erledigt und auch nicht mehr auf Nachrichten reagiert hat, wodruch manche Muss Kriterien
nicht erfüllt werden konnten.




== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
Das Reinarbeiten in die Frameworks war Anfangs sehr schwierig, vor allem weil die Dokumentation für Salespoint verbesserungswürdig war.
Durch die Hilfe des Videoshops wurde dies dann aber verständnissvoller.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
Es sollte vielleicht über eine Einkürzung des Projektes nachgedacht werden,
da der Zeitaufwand in einigen Wochen sehr hoch war und es teilweise sehr schwer macht, sich ausreichend auf
andere Studienfächer zu konzentrieren.

== Feedback für den Tutor
Wir hatten sehr viel Glück mit unserem Tutor. Durch seine langfrisitge Erfahrung konnte er uns sehr viele Tipps
und Lösungswege geben, was das Projekt teilweise stark vereinfachte. Er erklärte uns sehr detailiert, was in jeder
Dokumentation gefordert war, wodurch sich sehr viele Fragen beantworteten. Er war immer offen für Fragen und unsere Probleme
und wusste genau, worauf wir am meisten achten müssen. Er gab uns sehr oft einen Schubs in die richtige Richtung,
auch wenn wir nicht immer seinen Rat annahmen und sehr schwierig zu führen waren. Er hatte sehr viel Geduld mit uns
und hat uns nie aufgegeben.
Genauso stelle ich mir einen guten Tutor vor und kann nur hoffen, dass andere Tutoren genauso engagiert sind wie er.


== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
