= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2019/20
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Lee, Sanghyun

**Gruppe:** 43

== Was habe ich gelernt?
- Gruppenarbeit
: Besonders die Wichtigkeit der Kommunikation

- Java Kenntnisse

- Zeitmanagement

- Arbeit mit Framework

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
- Ich kann nicht so gut Deutsch sprechen. Deswegen habe ich etwas wenig im Team kommuniziert
und habe am Anfang ziemlich viele Stunden etwas anderes verschwendet. Durch dieses Projekt habe
ich gelernt, dass man viel kommunizieren muss. Durch die Kommunikation kann ich meine Zeit und Arbeit
ersparen.

- Wichtigket des Plans.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
- Salespoint ist ein sehr nutzbares Framework. Ich habe Salespoint in Prototyp genutzt und hatte einen
guten Eindruck. Die Salespoint-Dokumentationen war etwas unübersichtlich.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
- Es wird besser, wenn SWT Projekt in Vorlesungsfreie Zeit wie RoboLab führt aus.
Während des Semester war ich unter einem sehr hohen Zeitdruck. Sonst habe ich sehr viel gelernt.

== Feedback für den Tutor
Mein erster Eindruck vom Tutor (Uwe) war streng, aber ist er geduldig und versucht immer uns zu helfen.
Uwe ist meiner Meinung nach der besten. Ich bin sehr glücklich, dass Uwe unserer Tutor ist.
Ich bedanke Uwe.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
