= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2019/20
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Albert Wellerdt

**Gruppe:** 43

== Was habe ich gelernt?
- Arbeit mit Frameworks
Aufbau und Planung großer Projekte (z.B. wie wichtig die Analysephase ist und wie man mit guter Planung die
großen Probleme bei der Implementierung vermeiden kann)
- Java Kenntnisse
- Arbeiten in einer großen Gruppe

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Am Anfang hatten wir keinen roten Faden und keinen konkreten Plan als Team. Dies hat sich in der laufenden Zeit geändert.
Es war aber immer etwas schwierig, weil oft scheiterte einen gemeinsamen Termin zu finden, wo man sich als Gruppe hätte
treffen können. Auch die unterschiedliche Geschwindigkeit der einzelnen Gruppenmitglieder war eine große Herausforderungen.
Andere waren sofort an der Aufgabe, andere haben sich viel Zeit gelassen. Aber ich bin der Meinung das wir auch das gut
hingekriegt haben. Es ist natürlich schwierig mit 7 Leuten an einem Projekt zu arbeiten, was aber auch eine sehr gute
Erfahrung war.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Salespoint ist ein sehr schönes Framework, aber die Dokumentation könnte besser sein. Sie könnte mehr erklären was einzelne
Komponenten in dem Framework tun. Für mich war die Dokumentation leider sehr unübersichtlich.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Ich sehe die Gruppenbewertung als schwierig an. Sie ist einfacher auf der einen Seite, aber immer nur dann anwendbar wenn
jeder aus der Gruppe die gleich Arbeit geleistet hat. Sonst sind Leute im Vorteil die sehr wenig machen. Ich denke hier
könnte man variabler Entscheiden.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Ich fand die Zusammenarbeit sehr gut unserem Tutor. Am Anfang wirkte er sehr streng und mit hohen Erwartungen, die wir leider
nicht ganz erfüllen konnten. Er war sehr fair und um unser Wohlergehen bemüht. Ich habe viel durch ihn gelernt, Dinge die ich
das nächste Mal unbedingt ändern möchte.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
Die Dokumentation von Salespoint könnte bessere Erklärungen beinhalten und die Strukturierung könnte klarer gemacht werden.
