= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2019/20
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Isabell Zorr

**Gruppe:** 43

== Was habe ich gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Das Arbeiten mit und Verwenden von größeren Frameworks. Hier vor allem die Einschätzung, welche Features für meine
Probleme und meine Arbeit relevant sind. Auch die gezieltere Suche nach Stichwörtern, die mir bei meinen Problemen helfen
können. Zu guter Letzt noch grundlegende Java Kenntnisse und die Organisation von und Arbeit in einer Gruppe.

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Zunächst, dass es wichtig ist, von Anfang an einen konkreten Plan mit rotem Faden für ein Projekt zu haben, mit klarer
Aufgabenstellung. Das macht etwaige Einarbeitung neuer Gruppenmitglieder zu egal welchem Stand der Software einfacher.
Retroperspektiv gesehen. +
Schwieriger wurde es bei den verschiedenen Menschentypen in einer Gruppe. Die einen fangen sofort mit einer Aufgabe an,
andere lassen es ruhiger angehen, fangen eventuell mit einer geistigen Planung an, ehe sie Code in die Datei und auf
Github bringen. Wenn Person A von Person B abhängig ist, wird es schwierig einen gleichmäßgen Arbeitsfluss zu generieren.
Nicht, dass wir das in unserer Gruppe zu irgendeinem Zeitpunkt erreicht haben, aber es ist auf jeden Fall etwas, womit
in der Praxis stets zu rechnen ist. +
Desweiteren ist die unterschiedliche Arbeitsmoral ebenfalls ein Hindernis, und je nachdem wie man das handhabt, ein
großes oder ein Projekt zerstörendes. Manch einer hatte am Anfang Probleme sich in die Gruppe einzufinden und manch
ein anderer entschied auf den letzten Metern er müsse einfach gar nichts mehr machen. Ohne Vorwarnung, ohne Begründung.
In vielen Kreisen ist dies ein nicht tolerierter Akt und auch wir restlichen Mitglieder dulden solch unkameradschaftliches
Verhalten nicht. +
Dennoch habe ich für mich gelernt, dass man nie in einer Gruppenarbeit wirklich für sich fertig wird. +
Hat man seine Aufgaben fertig, sollte man stets versuchen, an anderer Stelle zu arbeiten oder anderen unter die Arme
zu greifen.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Zu Projektbeginn sollte man sich stets mit der Dokumentation des Frameworks vertraut machen, damit man bei Problemen
direkt auf diese zur Lösungsfindung zurückgreifen kann. Für Einsteiger, wie mich, war es zunächst schwierig mit einem
doch recht großen Framework wie Salespoint zu arbeiten, doch sobald ich ungefähr wusste, wie ich mich zurechtfinden kann,
hat es mir einige Arbeit erspart. Ich freue mich schon auf die Frameworkfindung in zukünftigen Projekten von mir.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Bitte keine Gruppenbewertung mehr. Klar, steigert das das Gruppenzusammenleben, wenn alle zusammen bestehen wollen, aber
so gibt es auch stets die Möglichkeit für einzelne Mitglieder sich durchschleifen zu lassen.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Ich habe mich sehr gut aufgehoben gefühlt bei unserem Tutor. Am Anfang wirkte er sehr streng und mit hohen Erwartungen
(die er unseretwegen sehr mindern musste). Doch er war stets fair und um unser Wohlergehen bemüht, hat uns auch
praxisnahe Anforderungen gestellt und uns Erfahrungen aus der Praxis vermittelt, weshalb er diese Anforderungen stellt.
Somit kam ein gutes Gefühl der Transparenz zustande und Fragen wie "Warum muss ich das jetzt machen??" kamen entweder gar
nicht auf oder wurden schnell beantwortet.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
Die Dokumentation von Salespoint ist teilweise so umfangreich und doch nichtssagend. Methoden werden mit offensichtlichen
Erklärungen erklärt und vielversprechende Verlinkungen gaben oft auch nichts Neues her.
